name: CI

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:

  sync:
    if: github.even.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      P4_STREAM_DEPOT: ${{ vars.P4_STREAM_DEPOT }}  # Name of the stream depot to sync to.
      P4_DEV_BRANCH_NAME: ${{ vars.P4_DEV_BRANCH_NAME }}  # Name of the dev branch.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Complete history

      - name: Install git-p4 & P4 CLI
        run: |
          sudo apt-get install git -y
          curl -fsSL https://filehost.perforce.com/perforce/r25.2/bin.linux26x86_64/p4 \
            -o /usr/local/p4
          chmod +x /usr/local/bin/p4

      - name: Configure P4 credentials
        env:
          P4PORT:   ${{ secrets.P4PORT }}
          P4USER:   ${{ secrets.P4USER }}
          P4PASSWD: ${{ secrets.P4PASSWD }}
          P4CLIENT: ${{ secrets.P4CLIENT }}
        run: |
          p4 login -p <<< "$P4PASSWD"
          p4 trust -y

      - name: Determine target P4 path
        id: p4path
        run: |
          BRANCH="${{ github.base_ref }}"
          if [ "$BRANCH" = "main" ]; then
            echo "path=//${{ env.P4_STREAM_DEPOT }}/main" >> $GITHUB_OUTPUT
          elif [ "$BRANCH" = "${{ env.P4_STREAM_DEPOT }}" ]; then
            echo "path=//${{ env.P4_STREAM_DEPOT }}/${{ env.P4_STREAM_DEPOT }}" >> $GITHUB_OUTPUT
          fi

      - name: Sync Git to Perforce
        env:
          P4PORT:   ${{ secrets.P4PORT }}
          P4USER:   ${{ secrets.P4USER }}
          P4CLIENT: ${{ secrets.P4CLIENT }}
        run: |
          git config git-p4.skipSubmitEdit true
          git p4 submit \
            --origin "origin/${{ github.base_ref }}" \
            --depot-path "${{ steps.p4path.outputs.path }}/..."
